article/urls.py
from django.urls import path
from .views import home, category, post, page

app_name='article'

urlpatterns = [
    path('', home, name='home'),
    path('category/<str:slug>', category, name='category'),
    path('article/<str:slug>', post, name='post'),
    path('page/<str:slug>', page, name='page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.utils.html import format_html
from django.utils import timezone
from category.models import Category
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
import datetime, time

# Create your models here.
class Article(models.Model):
	TYPE_CHOICES = (
		('post', 'پست'),
		('page', 'برگه')
	)
	type_article = models.CharField(max_length=4, choices=TYPE_CHOICES, default='post', verbose_name="نوع")
	title = models.CharField(max_length=200, verbose_name='عنوان')
	slug = models.SlugField(unique=True, verbose_name='آدرس')
	description = models.TextField(verbose_name='خلاصه')
	content = RichTextUploadingField(verbose_name='محتوای اصلی')
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='دسته بندی', help_text='درصورتی که نوع "برگه" را انتخاب کرده اید، این گزینه را رها کنید.')
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='نویسنده')
	image = models.ImageField(upload_to=time.strftime('%Y/%m/%d'), verbose_name='عکس مطلب', null=True, blank=True)
	image_popular = ImageSpecField(source='image',
							 processors=[ResizeToFill(100, 85)],
							 format='JPEG',
							 options={'quality': 60})
	image_featured = ImageSpecField(source='image',
							 processors=[ResizeToFill(350, 240)],
							 format='JPEG',
							 options={'quality': 60})
	image_category = ImageSpecField(source='image',
							 processors=[ResizeToFill(400, 275)],
							 format='JPEG',
							 options={'quality': 60})
	image_main = ImageSpecField(source='image',
							 processors=[ResizeToFill(840, 420)],
							 format='JPEG',
							 options={'quality': 60})
	image_event = ImageSpecField(source='image',
							 processors=[ResizeToFill(400, 650)],
							 format='JPEG',
							 options={'quality': 60})
	publish = models.DateTimeField(default=timezone.now, verbose_name='تاریخ انتشار')
	status = models.BooleanField(verbose_name='نمایش داده شود؟')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def image_tag(self):
		return format_html("<img src='{}' width=80 height=40>".format(self.image_popular.url))

	def author_name(self):
		if self.author.first_name and self.author.last_name:
			return "{} {}".format(self.author.first_name, self.author.last_name)
		elif self.author.first_name:
			return self.author.first_name
		elif self.author.last_name:
			return self.author.last_name
		else:
			return self.author

	class Meta:
		ordering = ('-publish',)
		verbose_name = "مقاله"
		verbose_name_plural = "مقالات"

	def __str__(self):
		return self.title

category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
	title = models.CharField(max_length=32, verbose_name='عنوان دسته')
	slug = models.SlugField(unique=True, verbose_name="آدرس دسته", help_text="باید منحصر به فرد باشد.")
	status = models.BooleanField(verbose_name='نمایش داده شود؟')
	position = models.PositiveIntegerField(default=0, verbose_name='جایگاه', help_text="بزرگترین عدد در ابتدا نمایش داده می شود.")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('-position', 'created')
		verbose_name = "دسته بندی"
		verbose_name_plural = "دسته بندی ها"

	def __str__(self):
		return self.title

article/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article
from category.models import Category
from django.core.paginator import Paginator


# Create your views here.
def home(request):
	events = Article.objects.filter(category__slug='events', status=True)[:3]
	return render(request, 'article/home.html', {'events': events,})

def category(request, slug):
	category = get_object_or_404(Category, status=True, slug=slug)
	articles_list = category.article_set.filter(status=True)
	page = request.GET.get('page', 1)
	paginator = Paginator(articles_list, 10)
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)
	context = {
		'category': category,
		'articles': articles,
	}
	return render(request, 'article/category.html', context)

def post(request, slug):
	context = {
		'article': get_object_or_404(Article, status=True, slug=slug, type_article='post'),
	}
	return render(request, 'article/single.html', context)

def page(request, slug):
	context = {
		'article': get_object_or_404(Article, status=True, slug=slug, type_article='page'),
	}
	return render(request, 'article/single.html', context)

category/views.py
from django.shortcuts import render

# Create your views here.

templates/article/category.html
{% extends 'article/base.html' %}

{% load news_area %}

{% block main %}        <!-- header start -->
			<!-- hero-area start -->
			<!-- ads -->
			<!-- <div class="page-banner-area mt-60">
				<div class="container">
					<div class="row">
						<div class="col-12">
							<div class="page-title-bar text-center pt-60 pb-60" style="background-image: url(assets/img/bg/page-itle.jpg)">
								<h1>Blog List View</h1>
							</div>
						</div>
					</div>
				</div>
			</div> -->
			<!-- hero-area end -->

			<!-- news area -->
			<section class="news-area pt-4 pb-60">
				<!-- trendy news -->
				<div class="container">
					<div class="row">
						<div class="col-xl-8 col-lg-8 col-md-12">
							<h2 class="container h4 px-0 pb-3">دسته بندی: <span>{{category.title}}</span></h2>
							{% for article in articles %}
								<div class="postbox mb-40">
									<div class="postbox__thumb mb-25">
										<a href="{% url 'article:post' article.slug %}">
											<img src="{{article.image_main.url}}" alt="{{article.title}}">
										</a>
									</div>
									<div class="postbox__text">
										<div class="postbox__text-meta pb-20">
											<ul>
												<li>
													<i class="fas fa-calendar-alt"></i>
													<span>{{article.publish}}</span>
												</li>
												<li>
													<i class="far fa-comment"></i>
													<span>(03)</span>
												</li>
											</ul>
										</div>
										<h4 class="title-30 font-600 pr-0">
											<a href="{% url 'article:post' article.slug %}">{{ article.title }}</a>
										</h4>
										<div class="desc-text mb-20">
											<p>{{ article.description }}</p>
										</div>
										<a href="{% url 'article:post' article.slug %}" class="read-more btn f-left">بیشتر</a>
										<div class="clearfix"></div>
									</div>
								</div>
							{% empty %}

							{% endfor %}
						</div>
						<div class="col-xl-4 col-lg-4 col-md-12">
							<!-- ads -->
							<!-- <div class="widget mb-40">
								<a href="#">
									<img src="assets/img/add/add-sidebar.jpg" alt="">
								</a>
							</div> -->
							<div class="widget widget-border mb-40">
								<h3 class="widget-title">Popular posts</h3>
								<div class="post__small mb-30">
									<div class="post__small-thumb f-left">
										<a href="#">
											<img src="assets/img/trendy/xs/xs-1.jpg" alt="hero image">
										</a>
									</div>
									<div class="post__small-text fix pl-10">
										<span class="sm-cat">
											<a href="#">Fashion</a>
										</span>
										<h4 class="title-13 pr-0">
											<a href="#">Husar asks expenses authority to entitlements after Bruno</a>
										</h4>
										<div class="post__small-text-meta">
											<ul>
												<li>
													<i class="fas fa-calendar-alt"></i>
													<span>01 Sep 2018</span>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<div class="post__small mb-30">
									<div class="post__small-thumb f-left">
										<a href="#">
											<img src="assets/img/trendy/xs/xs-2.jpg" alt="hero image">
										</a>
									</div>
									<div class="post__small-text fix pl-10">
										<span class="sm-cat">
											<a href="#">Fashion</a>
										</span>
										<h4 class="title-13 pr-0">
											<a href="#">Researchers claim majo throug in the fight to cure fibrosis</a>
										</h4>
										<div class="post__small-text-meta">
											<ul>
												<li>
													<i class="fas fa-calendar-alt"></i>
													<span>01 Sep 2018</span>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<div class="post__small mb-30">
									<div class="post__small-thumb f-left">
										<a href="#">
											<img src="assets/img/trendy/xs/xs-3.jpg" alt="hero image">
										</a>
									</div>
									<div class="post__small-text fix pl-10">
										<span class="sm-cat">
											<a href="#">Fashion</a>
										</span>
										<h4 class="title-13 pr-0">
											<a href="#">Nahan downplays Liberal lership tensions after white ant</a>
										</h4>
										<div class="post__small-text-meta">
											<ul>
												<li>
													<i class="fas fa-calendar-alt"></i>
													<span>01 Sep 2018</span>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<div class="post__small">
									<div class="post__small-thumb f-left">
										<a href="#">
											<img src="assets/img/trendy/xs/xs-4.jpg" alt="hero image">
										</a>
									</div>
									<div class="post__small-text fix pl-10">
										<span class="sm-cat">
											<a href="#">Travel</a>
										</span>
										<h4 class="title-13 pr-0">
											<a href="#">Farmers plead for bullets to put down emaciated stock</a>
										</h4>
										<div class="post__small-text-meta">
											<ul>
												<li>
													<i class="fas fa-calendar-alt"></i>
													<span>01 Sep 2018</span>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div class="widget widget-border mb-40">
								<h3 class="widget-title">Categories</h3>
								<ul>
									<li><a href="#">Business</a></li>
									<li><a href="#">Politic</a></li>
									<li><a href="#">Fashion</a></li>
									<li><a href="#">Corporate</a></li>
									<li><a href="#">Football</a></li>
									<li><a href="#">Magazine</a></li>
								</ul>
							</div>
						</div>
					</div>
					{% include 'article/parts/paginator.html' with contents=articles %}
				<!-- trendy news end -->
			</section>
			<!-- news area end -->
{% endblock %}

templates/article/home.html
{% extends 'article/base.html' %}

{% load news_area %}

{% block main %}

    <!-- news area -->
    <section class="news-area py-3"><!-- pt-60 -->
        <!-- trendy news -->
        {% news_area_last_3 'free-software' %}
        {% news_area_last_3 'gnu-linux' %}
        {% news_area_last_3 'podcast' %}
        <!-- trendy news end -->
    </section>
    <!-- news area end -->

    <!-- blog-lg-area start -->
    {% if events %}
    <div class="blog-lg-area pt-10">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="row">
                        <h2 class="container h4 px-0 pb-3"><a href="{% url 'article:category' 'events' %}">رویدادها</a></span></h2>
                        {% for event in events %}
                        <div class="col-xl-4 col-md-4">
                            <div class="post__features blog-no-border  mb-30">
                                <div class="post__features-thumb blog-opacity" data-overlay="dark-gradient">
                                    <a href="{% url 'article:post' event.slug %}">
                                        <img class="img-100" src="{{event.image_event.url}}" alt="{{event.title}}">
                                    </a>
                                </div>
                                <div class="post__features-content">
                                    <h4 class="title-24 font-600">
                                        <a href="{% url 'article:post' event.slug %}">{{event.title}}</a>
                                    </h4>
                                    <div class="postbox__text-meta red-meta">
                                        <ul>
                                            <li>
                                                <i class="fas fa-calendar-alt"></i>
                                                <span>{{event.publish}}</span>
                                            </li>
                                            <li>
                                                <i class="far fa-comment"></i>
                                                <span>(۴۱)</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <!-- blog-lg-area end -->
{% endblock %}

templates/article/parts/news_area.html
{% if articles %}
    <div class="container position-relative">
        <h2 style="top: -1rem; right: 0;" class="d-table position-absolute bg-white px-4 h4"><a href="{% url 'article:category' category.slug %}">{{category.title}}</a></h2>
        <span style="top: -0.75rem; left: 0; font-size: 0.75rem" class="d-table position-absolute bg-white px-4"><a href="{% url 'article:category' category.slug %}">بیشتر</a></span>
        <div class="row border-top pt-4 mt-4">
            {% for article in articles %}
                <div class="col-xl-4 col-lg-4 col-md-6">
                    <div class="postbox mb-40">
                        <div class="postbox__thumb mb-25">
                            <a href="{% url 'article:post' article.slug %}">
                                <img src="{{article.image_category.url}}" alt="{{article.title}}">
                            </a>
                        </div>
                        <div class="postbox__text">
                            <div class="postbox__text-meta pb-20">
                                <ul>
                                    <li>
                                        <i class="fas fa-calendar-alt"></i>
                                        <span>{{article.publish}}</span>
                                    </li>
                                    <li>
                                        <i class="far fa-comment"></i>
                                        <span>(۴۱)</span>
                                    </li>
                                </ul>
                            </div>
                            <h4 class="title-18 font-600 pr-0">
                                <a href="{% url 'article:post' article.slug %}">{{article.title}}</a>
                            </h4>
                            <div class="desc-text mb-20">
                                <p>{{article.description}}</p>
                            </div>
                            <a href="{% url 'article:post' article.slug %}" class="read-more btn">بیشتر</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

templates/article/parts/paginator.html
					{% if contents.has_other_pages %}
					<div class="row mt-10">
						<div class="col-xl-12">
							<div class="pagination">
								<ul>
									{% if contents.has_previous %}
									<li>
										<a href="?page={{ contents.previous_page_number }}">قبل</a>
									</li>
									{% else %}
									<li>
										<span>قبل</span>
									</li>
									{% endif %}
									{% for i in contents.paginator.page_range %}
										{% if contents.number == i %}
											<li class="active">
												<span>{{ i }}</span>
											</li>
										{% else %}
											<li>
												<a href="?page={{ i }}">
													{{ i }}
												</a>
											</li>
										{% endif %}
									{% endfor %}
									{% if contents.has_next %}
										<li>
											<a href="?page={{ contents.next_page_number }}">بعد</a>
										</li>
									{% else %}
										<li>
											<span>بعد</span>
										</li>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
				</div>
				{% endif %}

templates/article/parts/show_categories.html
<ul>
    <li><a href="{% url 'article:home' %}">خانه</a></li>
    {% for category in categories %}
	    <li><a href="{% url 'article:category' category.slug %}">{{category.title}}</a></li>
	{% empty %}
		<li><a href="">هیچ دسته بندی یافت نشد.</a></li>
	{% endfor %}
    <li><a href="politic.html">فروم</a></li>
    <li><a href="politic.html">ویکی</a></li>
</ul>

templates/article/single.html
{% extends 'article/base.html' %}

{% block main %}
	<section class="post-details-area pt-60 pb-30">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-8">
					 <!-- post-details -->
					<div class="post-details">
						<h2 class="details-title mb-15">{{article.title}}</h2>

						{% if article.type_article == 'post' %}
						<!-- meta -->
						<div class="postbox__text-meta pb-30">
							<ul>
								<li>
									<i class="far fa-user-circle"></i>
									<span>{{article.author_name}}</span>
								</li>
								<li>
									<i class="fas fa-calendar-alt"></i>
									<span>{{article.publish}}</span>
								</li>
								<li>
									<i class="far fa-comment"></i>
									<span>(۴۱)</span>
								</li>
							</ul>
						</div>
						{% endif %}

						 <!-- share-post-link -->
						<div class="share-post-link mb-30">
							<a class="facebook" href="#">
								<i class="fab fa-facebook-f"></i>
							</a>
							<a class="twitter" href="#">
								<i class="fab fa-twitter"></i>
							</a>
							<a class="instagram" href="#">
								<i class="fab fa-instagram"></i>
							</a>
							<a class="dribbble" href="#">
								<i class="fab fa-dribbble"></i>
							</a>
							<a class="pinterest" href="#">
								<i class="fab fa-pinterest-p"></i>
							</a>
							<a class="google-plus" href="#">
								<i class="fab fa-google-plus-g"></i>
							</a>
							<a class="pinterest" href="#">
								<i class="fab fa-pinterest-p"></i>
							</a>
						</div>

						{% if article.image %}
						 <!-- post-thumb -->
						<div class="post-thumb mb-25">
							<img src="{{article.image_main.url}}" alt="{{article.title}}">
						</div>
						{% endif %}

						<!-- post-content -->
						<div class="post-content">
							{{article.content|safe}}
						</div>

						<!-- content__tags -->
						<!-- <div class="content__tags mt-30">
							<span>Post Tags:</span>
							<span class="content__tags-list">
								<a href="#0">orci</a>
								<a href="#0">lectus</a>
								<a href="#0">varius</a>
								<a href="#0">turpis</a>
							</span>
						</div> -->
						{% if article.type_article == 'post' %}
						 <!-- author-meta -->
						<div class="author-meta  mt-60">
							<div class="media flex-column flex-md-row">
								<div class="media-left">
									<a href="#"><img src="assets/img/user/user-03.jpg" alt=""> </a>
								</div>
								<div class="media-body">
									<span class="media-heading">
										<a href="#">Richard</a>
									</span>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipi sicing elit, sed do eiu smod tempor ut laboredolore magna aliqua. Ut enim ad
										minim doing veniam, quis nostrud exerci tation ullamco laboris nisi. </p>
									<div class="social">
										<a href="https://www.facebook.com/" target="_blank">
											<i class="fab fa-facebook-f"></i>
										</a>
										<a href="https://twitter.com/" target="_blank">
											<i class="fab fa-twitter"></i>
										</a>
										<a href="https://plus.google.com/discover" target="_blank">
											<i class="fab fa-google-plus-g"></i>
										</a>
										<a href="https://www.instagram.com/" target="_blank">
											<i class="fab fa-linkedin-in"></i>
										</a>
									</div>
								</div>
							</div>
						</div>

						 <!-- post-comments -->
						<div class="post-comments mt-30">
							<div class="section-title mb-30">
								<h2>Recent Comments</h2>
							</div>
							<div class="latest-comments">
								<ul>
									<li>
										<div class="comments-box">
											<div class="comments-avatar">
												<img src="assets/img/user/user-01.jpg" alt="">
											</div>
											<div class="comments-text">
												<div class="avatar-name">
													<h5>Omar Elnagar</h5>
													<span>September 13, 2018 at 10:38 AM</span>
												</div>
												<p>They call him Flipper Flipper faster than lightning. No one you see is smarter than he. They call
													him Flipper Flipper the faster than lightning. No one you see is smarter than he</p>
												<a href="#"><i class="fas fa-reply-all"></i> Reply</a>
											</div>
										</div>
										<ul class="comments-reply">
											<li>
												<div class="comments-box">
													<div class="comments-avatar">
														<img src="assets/img/user/user-02.jpg" alt="">
													</div>
													<div class="comments-text">
														<div class="avatar-name">
															<h5>Omar Elnagar</h5>
															<span>September 13, 2018 at 10:38 AM</span>
														</div>
														<p>They call him Flipper Flipper faster than lightning. No one you see is smarter than he. They
															call him Flipper Flipper the faster than lightning. No one you see is smarter than he</p>
														<a href="#"><i class="fas fa-reply-all"></i> Reply</a>
													</div>
												</div>
											</li>
										</ul>
									</li>
									<li>
										<div class="comments-box">
											<div class="comments-avatar">
												<img src="assets/img/user/user-05.jpg" alt="">
											</div>
											<div class="comments-text">
												<div class="avatar-name">
													<h5>Omar Elnagar</h5>
													<span>September 13, 2018 at 10:38 AM</span>
												</div>
												<p>They call him Flipper Flipper faster than lightning. No one you see is smarter than he. They call
													him Flipper Flipper the faster than lightning. No one you see is smarter than he</p>
												<a href="#"><i class="fas fa-reply-all"></i> Reply</a>
											</div>
										</div>
									</li>
								</ul>
							</div>
						</div>

						 <!-- post-comments-form -->
						<div class="post-comments-form mt-40 mb-40">
							<div class="section-title mb-30">
								<h2>Recent Comments</h2>
							</div>
							<form action="#">
								<div class="row">
									<div class="col-xl-6">
										<input type="text" placeholder="Your Name">
									</div>
									<div class="col-xl-6">
										<input type="text" placeholder="Your Email">
									</div>
									<div class="col-xl-12">
										<textarea name="comments" id="comments" cols="30" rows="10" placeholder="Your Comments"></textarea>
										<button class="btn brand-btn" type="submit">Send message</button>
									</div>
								</div>
							</form>
						</div>
						{% endif %}
					</div>
				</div>
				<div class="col-xl-4 col-lg-4">
					<div class="widget widget-border mb-40">
						<h3 class="widget-title">Popular posts</h3>
						<div class="post__small mb-30">
							<div class="post__small-thumb f-left">
								<a href="#">
									<img src="assets/img/trendy/xs/xs-1.jpg" alt="hero image">
								</a>
							</div>
							<div class="post__small-text fix pl-10">
								<span class="sm-cat">
									<a href="#">Fashion</a>
								</span>
								<h4 class="title-13 pr-0">
									<a href="#">Husar asks expenses authority to entitlements after Bruno</a>
								</h4>
								<div class="post__small-text-meta">
									<ul>
										<li>
											<i class="fas fa-calendar-alt"></i>
											<span>01 Sep 2018</span>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="post__small mb-30">
							<div class="post__small-thumb f-left">
								<a href="#">
									<img src="assets/img/trendy/xs/xs-2.jpg" alt="hero image">
								</a>
							</div>
							<div class="post__small-text fix pl-10">
								<span class="sm-cat">
									<a href="#">Fashion</a>
								</span>
								<h4 class="title-13 pr-0">
									<a href="#">Researchers claim majo throug in the fight to cure fibrosis</a>
								</h4>
								<div class="post__small-text-meta">
									<ul>
										<li>
											<i class="fas fa-calendar-alt"></i>
											<span>01 Sep 2018</span>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="post__small mb-30">
							<div class="post__small-thumb f-left">
								<a href="#">
									<img src="assets/img/trendy/xs/xs-3.jpg" alt="hero image">
								</a>
							</div>
							<div class="post__small-text fix pl-10">
								<span class="sm-cat">
									<a href="#">Fashion</a>
								</span>
								<h4 class="title-13 pr-0">
									<a href="#">Nahan downplays Liberal lership tensions after white ant</a>
								</h4>
								<div class="post__small-text-meta">
									<ul>
										<li>
											<i class="fas fa-calendar-alt"></i>
											<span>01 Sep 2018</span>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="post__small">
							<div class="post__small-thumb f-left">
								<a href="#">
									<img src="assets/img/trendy/xs/xs-4.jpg" alt="hero image">
								</a>
							</div>
							<div class="post__small-text fix pl-10">
								<span class="sm-cat">
									<a href="#">Travel</a>
								</span>
								<h4 class="title-13 pr-0">
									<a href="#">Farmers plead for bullets to put down emaciated stock</a>
								</h4>
								<div class="post__small-text-meta">
									<ul>
										<li>
											<i class="fas fa-calendar-alt"></i>
											<span>01 Sep 2018</span>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="widget widget-border mb-40">
						<h3 class="widget-title">Categories</h3>
						<ul>
							<li><a href="#">Business</a></li>
							<li><a href="#">Politic</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Corporate</a></li>
							<li><a href="#">Football</a></li>
							<li><a href="#">Magazine</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}